name: construction
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Start Packages
  flutter_screenutil: ^5.7.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.19
  getwidget: ^3.0.1
  # End Packages

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#DC8449"
  image: assets/images/splash_logo.png
  android_gravity: center


flutter:

  uses-material-design: true
  assets:
    - assets/images/splash_logo.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
